### ISSUE TITLE
Using metric for each sentence in a file

### ISSUE THREAD

**Issue by sugeeth14** [DeepLearnXMU/Otem-Utem#1]
Hi, I want to know the score of OTEM and UTEM scores  for each sentence in a file. Please help me in getting scores as such.
Thanks in advance

**Comment by bzhangGo** [comment]
Hi @Raghava14 ,
The scripts in current version only support corpus-level evaluation scores, rather than sentence-level. As a trivial solution, you can perform sentence-level evaluation by feeding data in a sentence-wise manner. 

Our project is still under developing. Your suggestion is great. We will support these requirements as soon as possible.

**Comment by sugeeth14** [comment]
That would be great thanks !! @bzhangXMU

**Comment by bzhangGo** [comment]
Please see the test.py for reference.
